
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usama
 */
public class LoginScreen extends javax.swing.JFrame implements WindowListener{

    /**
     * Creates new form LoginScreen
     */
    
    public LoginScreen() {
        initComponents();
        this.setTitle("Walmart Supervision System");
//        setBounds(800, 800, 420, 200);
        setSize(695, 521);
        setLocation(420, 100);
//        ComboBoxRole.addItem("Chief");
//        ComboBoxRole.addItem("Supervisor");
        DB.connAndLogins();
        
        
        ComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Chief", "Supervisor" }));
        
        
            
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameT = new javax.swing.JTextField();
        passwordT = new javax.swing.JPasswordField();
        loginB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxRole = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME TO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 130, 130, 21);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SUPERVISION SYSTEM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 260, 180, 21);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME/ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 310, 110, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 350, 80, 20);

        usernameT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTActionPerformed(evt);
            }
        });
        getContentPane().add(usernameT);
        usernameT.setBounds(390, 300, 126, 30);
        getContentPane().add(passwordT);
        passwordT.setBounds(390, 340, 126, 30);

        loginB.setBackground(new java.awt.Color(255, 255, 255));
        loginB.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        loginB.setForeground(new java.awt.Color(51, 51, 255));
        loginB.setText("LOGIN");
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });
        getContentPane().add(loginB);
        loginB.setBounds(250, 420, 170, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("YOUR ROLE:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 390, 73, 15);

        ComboBoxRole.setBackground(new java.awt.Color(255, 231, 3));
        ComboBoxRole.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        ComboBoxRole.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboBoxRole);
        ComboBoxRole.setBounds(390, 380, 126, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_141224_em_walmart_12.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-10, 0, 690, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTActionPerformed

    private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed
        // TODO add your handling code here:
        String usernames[] = DB.username;
        String passwords[] = DB.password;
        String roles[] = DB.role;
        
        boolean chiefF = false;
        boolean supervisorF = false;
            
        while(true){
        if (usernameT.getText().equals("") || passwordT.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter username and password, both");
        else if(ComboBoxRole.getSelectedItem().toString().equals("Select"))
            JOptionPane.showMessageDialog(null, "Please select Job Role");
        else
            break;
        }
        
        String username = usernameT.getText();
        String password = passwordT.getText();
        String role = ComboBoxRole.getSelectedItem().toString();
            
                    
        //for Chief
        if(ComboBoxRole.getSelectedItem().toString().equals("Chief"))
        {
            //setting the chief flag
            for(int i=0;i<usernames.length;i++)
            {
               if(username.equals(usernames[i])&& password.equals(passwords[i]) )
               {
                    System.out.println(roles[i] + " " + usernames[i] + " " + passwords[i] );
                    if (role.equalsIgnoreCase(roles[i])){
                        chiefF = true;
                        
                    }
               }
            }
            if(chiefF==true)
            {
                JOptionPane.showMessageDialog(null, "Login Succesful!");
                new ChiefWindow().setVisible(true);
                this.setVisible(false);
                
            }
            else
                JOptionPane.showMessageDialog(null, "Login Failed!\nPlease enter correct Information i.e. Username and Password");
         }
        
         
         //for Supervisor
        if(ComboBoxRole.getSelectedItem().toString().equals("Supervisor"))
        {
            //setting the chief flag
            for(int i=0;i<usernames.length;i++)
            {
               if(username.equals(usernames[i])&& password.equals(passwords[i]) )
               {
                    System.out.println(roles[i] + " " + usernames[i] + " " + passwords[i] );
                    if (role.equalsIgnoreCase(roles[i])){
                        supervisorF = true;
                        
                    }
               }
            }
            if(supervisorF==true)
            {
                JOptionPane.showMessageDialog(null, "Login Succesful!");
                new SupervisorWindow().setVisible(true);
                this.setVisible(false);
                
            }
            else
                JOptionPane.showMessageDialog(null, "Login Failed!\nPlease enter correct Information i.e. Username and Password");}
    }//GEN-LAST:event_loginBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    @Override
    public void windowOpened(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosing(WindowEvent e) {
        int n = JOptionPane.showOptionDialog(new JFrame(), "Are you sure you want to leave?", "Confirm Please", JOptionPane.OK_OPTION, 
                JOptionPane.QUESTION_MESSAGE, null, new Object[] {"Yes", "No"}, JOptionPane.CANCEL_OPTION);
        switch (n){
            case JOptionPane.OK_OPTION:{
                
                System.exit(0);
                
            }
            case JOptionPane.CANCEL_OPTION:{
//                dispose();
                setVisible(true);
            }
        }
    }

    @Override
    public void windowClosed(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginB;
    private javax.swing.JPasswordField passwordT;
    private javax.swing.JTextField usernameT;
    // End of variables declaration//GEN-END:variables
}
